### ISSUE TITLE
"enable history" fails

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#177]
When I say "enable history", I get the following error message:

```
ERROR:action:Exception from function _:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\actions\action_function.py", line 109, in _execute
    self._function(**arguments)
  File "D:\Dropbox\NatLink\dragonfly\caster\lib\dfplus\merge\ccrmerger.py", line 148, in _
    self.merge(MergeInf.SELFMOD, name2, enable, save)
  File "D:\Dropbox\NatLink\dragonfly\caster\lib\dfplus\merge\ccrmerger.py", line 290, in merge
    for grammar in self._grammars: grammar.load()
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\grammar\grammar_base.py", line 327, in load
    rule.activate(force=True)
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\grammar\rule_base.py", line 203, in activate
    self._grammar.activate_rule(self)
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\grammar\grammar_base.py", line 256, in activate_rule
    self._engine.activate_rule(rule, self)
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\engines\backend_natlink\engine.py", line 165, in activate_rule
    grammar_object.activate(rule.name, 0)
BadGrammar: The grammar is too complex to be recognized
ERROR:action.exec:Execution failed: Function(_): The grammar is too complex to be recognized

```

When I say this, the rest of caster also seems to break. Any ideas for troubleshooting this?

UPDATE: It seems to work fine when I disable all the other grammars that I'm working with. I'm guessing this is a feature that stops Dragon from running too slow?

**Comment by synkarius** [comment]
Ah, you found our old friend BadGrammar. Try disabling a bunch of other
rules and then trying again. Tell me if it still happens with nothing else
enabled. (You can see what's enabled in ccr.json.)

**Comment by kendonB** [comment]
It seems to work fine when I disable all the other grammars that I'm working with. I'm guessing this is a feature that stops Dragon from running too slow? Can the "complexity" threshold be relaxed?

**Comment by kendonB** [comment]
In saying that, I can't think of a use case that relies on other grammars.

**Comment by chilimangoes** [comment]
The BadGrammar error is a restriction that happens at the Dragon NaturallySpeaking level, and I haven't seen any information on how the limit could be relaxed. @Synkarius did a pretty in-depth analysis and write up on the issue [here](http://explosionduck.com/wp/introduction-to-voice-programming-part-four-grammar-complexity/).

**Comment by synkarius** [comment]
As we discovered back then, the complexity limit is absolute and not hardware or Dragon version dependent, but there _were_ complexity cost tradeoffs which could be made. For example, by lowering the `max_ccr_repetitions` setting in settings.py, you can have more rules enabled, and vice versa. I don't think I have ever spoken a chain of more than 8 commands, but the Dragonfly default max (and thus the Caster default max) is 16. You might consider playing with that number if you want more CCR rules enabled simultaneously.
