### ISSUE TITLE
Running with only WSR?

### ISSUE THREAD

**Issue by mbpolan** [synkarius/caster#182]
I have a feeling I'm missing something simple here, but after going through the documentation I still cannot find an answer.  If I want to use caster with only WSR, do I need it any other modules installed besides dragonfly? I tried running _castor.py but it fails looking for Natlink it seems:

```
>python _caster.py
Cannot find default dragon engine path
Traceback (most recent call last):
  File "_caster.py", line 12, in <module>
    from caster.lib.ccr.standard import SymbolSpecs
  File "C:\Users\mike\Desktop\caster-master\caster\lib\ccr\__init__.py", line 1, in <module>
    from bash.bash import Bash
  File "C:\Users\mike\Desktop\caster-master\caster\lib\ccr\bash\bash.py", line 11, in <module>
    from caster.lib.dfplus.state.short import R
  File "C:\Users\mike\Desktop\caster-master\caster\lib\dfplus\state\short.py", line 7, in <module>
    from caster.lib.dfplus.state.actions import RegisteredAction
  File "C:\Users\mike\Desktop\caster-master\caster\lib\dfplus\state\actions.py", line 6, in <module>
    _NEXUS = control.nexus()
  File "C:\Users\mike\Desktop\caster-master\caster\lib\control.py", line 9, in nexus
    _NEXUS = Nexus()
  File "C:\Users\mike\Desktop\caster-master\caster\lib\ctrl\nexus.py", line 28, in __init__
    from dragonfly.timer import _Timer
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\timer.py", line 27, in <module>
    import natlink
ImportError: No module named natlink
```

Do I still need to install Natlink and friends, or is there some extra configuration that needs to be done so that caster only loads what it needs for WSR?

**Comment by Versatilus** [comment]
I've never tried it with WSR, but I do remember there being some issue which made the timer from NatLink necessary. I have no idea what state that section of code is in. It might not be terribly difficult to massage it into working shape, if you want to make a pass at it. 

Also, if your installation of Dragonfly isn't from the [GitHub repository](https://github.com/t4ngo/dragonfly), then it might be outdated.

**Comment by LexiconCode** [comment]
NatLink is not required for WRS
