### ISSUE TITLE
Error when attempting to run

### ISSUE THREAD

**Issue by anubisthejackle** [synkarius/caster#238]
```
Error loading _caster from C:\NatLink\NatLinkUserDirectory\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 322, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLinkUserDirectory\_caster.py", line 12, in <module>
    from caster.lib.ccr.standard import SymbolSpecs
  File "C:\NatLink\NatLinkUserDirectory\caster\lib\ccr\__init__.py", line 3, in <module>
    from core.nav import Navigation
  File "C:\NatLink\NatLinkUserDirectory\caster\lib\ccr\core\nav.py", line 10, in <module>
    from caster.lib.dfplus.additions import IntegerRefST
  File "C:\NatLink\NatLinkUserDirectory\caster\lib\dfplus\additions.py", line 2, in <module>
    from dragonfly.grammar.elements import RuleWrap, Choice
ImportError: cannot import name RuleWrap
```

Attempted to install NatLink, Dragonfly, and Caster from the YouTube videos, and this is what I get when I install.

Any idea what I'm doing wrong?

**Comment by anubisthejackle** [comment]
I followed the instructions in #217 and it's working now.
