### ISSUE TITLE
`enable alias` produces unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/Caster#24]
Reproduced consistently with `enable alias` does not occur with `enable chain alias`

```ERROR:action:Exception from function <lambda>:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_function.py", line 136, in _execute
    self._function(**arguments)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\grammar_activator.py", line 61, in <lambda>
    _mapping[enable_spec] = Function(lambda rcn: self._activation_fn(rcn, True), rcn=class_name)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 69, in <lambda>
    self._activator.set_activation_fn(lambda rcn, active: self._change_rule_active(rcn, active))
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 140, in _change_rule_active
    self._delegate_enable_rule(class_name, enabled)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 166, in _delegate_enable_rule
    self._enable_non_ccr_rule(managed_rule, enabled)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 202, in _enable_non_ccr_rule
    grammar = self._mapping_rule_maker.create_non_ccr_grammar(managed_rule)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\rule_maker\mapping_rule_maker.py", line 17, in create_non_ccr_grammar
    rule_instance = managed_rule.get_rule_class()(name=details.name)
TypeError: __init__() got an unexpected keyword argument 'name'
ERROR:action.exec:Execution failed: Function(<lambda>): __init__() got an unexpected keyword argument 'name'```

**Comment by LexiconCode** [comment]
confirmed that c653d4be056b0132b8a7891d5822ef324f5f9a3c fixes the error message.
