### ISSUE TITLE
_find_natspeak() function fails with AttributeError: winmgmts:.Win32_Product on some machines.

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/caster#248]
[Source](http://www.knowbrainer.com/forums/forum/messageview.cfm?catid=25&threadid=31216)

Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 322, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\user\_caster.py", line 30, in <module>
    from caster.lib import settings  # requires nothing
  File "C:\NatLink\NatLink\user\caster\lib\settings.py", line 109, in <module>
    "ENGINE_PATH": _validate_natspeak(),
  File "C:\NatLink\NatLink\user\caster\lib\settings.py", line 59, in _validate_natspeak
    return _find_natspeak()
  File "C:\NatLink\NatLink\user\caster\lib\settings.py", line 65, in _find_natspeak
    for p in w.Win32_Product():
  File "C:\Python27\lib\site-packages\wmi.py", line 1147, in __getattr__
    return getattr (self._namespace, attribute)
  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: winmgmts:.Win32_Product
-- skip unchanged wrong grammar file: C:\NatLink\NatLink\user\_caster.py
-- skip unchanged wrong grammar file: C:\NatLink\NatLink\user\_caster.py
natlinkmain started from C:\NatLink\NatLink\MacroSystem\core:
  NatLink version: 4.1victor
  DNS version: 15
  Python version: 27
  Windows Version: 7

**Comment by LexiconCode** [comment]
Self-Notes
A working example of powershell.
`Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallLocation | Format-Table -AutoSize`

**Comment by LexiconCode** [comment]
```
import errno, os, _winreg

def _find_natspeak():
    proc_arch = os.environ['PROCESSOR_ARCHITECTURE'].lower()
    proc_arch64 = os.environ['PROCESSOR_ARCHITEW6432'].lower()

    if proc_arch == 'x86' and not proc_arch64:
        arch_keys = {0}
    elif proc_arch == 'x86' or proc_arch == 'amd64':
        arch_keys = {_winreg.KEY_WOW64_32KEY, _winreg.KEY_WOW64_64KEY}
    else:
        raise Exception("Unhandled arch: %s" % proc_arch)

    for arch_key in arch_keys:
        key = _winreg.OpenKey(_winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall", 0, _winreg.KEY_READ | arch_key)
        for i in xrange(0, _winreg.QueryInfoKey(key)[0]):
            skey_name = _winreg.EnumKey(key, i)
            skey = _winreg.OpenKey(key, skey_name)
            try:
                DisplayName = _winreg.QueryValueEx(skey, 'DisplayName')[0]
                DisplayVersion = _winreg.QueryValueEx(skey, 'DisplayVersion')[0]
                InstallLocation = _winreg.QueryValueEx(skey, 'InstallLocation')[0]
                # print DisplayName
                # print DisplayVersion 
                # print InstallLocation
            except OSError as e:
                if e.errno == errno.ENOENT:
                    pass
            finally:
                skey.Close()
_find_natspeak()
```
