### ISSUE TITLE
Currently getting a startup error

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#28]
```
Error loading _caster from C:\Users\kmbel\Documents\caster\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\kmbel\Documents\caster\_caster.py", line 33, in <module>
    control.init_nexus(_content_loader)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\control.py", line 7, in init_nexus
    _NEXUS = Nexus(content_loader)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\nexus.py", line 79, in __init__
    self._load_and_register_all_content(rules_config, hooks_runner, transformers_runner)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\nexus.py", line 92, in _load_and_register_all_content
    self._grammar_manager.load_activation_grammars()
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 272, in load_activation_grammars
    self._change_rule_active(rc.__name__, True)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 140, in _change_rule_active
    self._delegate_enable_rule(class_name, enabled)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 166, in _delegate_enable_rule
    self._enable_non_ccr_rule(managed_rule, enabled)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 204, in _enable_non_ccr_rule
    grammar.load()
  File "C:\Python27\lib\site-packages\dragonfly\grammar\grammar_base.py", line 338, in load
    self._engine.load_grammar(self)
  File "C:\Python27\lib\site-packages\dragonfly\engines\base\engine.py", line 138, in load_grammar
    wrapper = self._load_grammar(grammar)
  File "C:\Python27\lib\site-packages\dragonfly\engines\backend_natlink\engine.py", line 112, in _load_grammar
    (compiled_grammar, rule_names) = c.compile_grammar(grammar)
  File "C:\Python27\lib\site-packages\dragonfly\engines\backend_natlink\compiler.py", line 48, in compile_grammar
    self._compile_rule(rule, compiler)
  File "C:\Python27\lib\site-packages\dragonfly\engines\backend_natlink\compiler.py", line 60, in _compile_rule
    self.compile_element(rule.element, compiler)
  File "C:\Python27\lib\site-packages\dragonfly\engines\base\compiler.py", line 78, in compile_element
    % (self, element))
NotImplementedError: Compiler NatlinkCompiler() not implemented for element type None.
```

**Comment by LexiconCode** [comment]
Confirmed

**Comment by synkarius** [comment]
I suspect this is related to what @Versatilus is experiencing here:
https://github.com/synkarius/Caster/pull/29
Will look into this later tonight.

**Comment by synkarius** [comment]
This is closely related to #29, though not exactly the same issue.

**Comment by synkarius** [comment]
e96b1e8b7908a4e27ec784c8579cd46c00eaa947 ought to take care of this. (I referenced the wrong bug numbers, so it didn't show up here.) See my conversation with @Versatilus in #29 about MappingRule vs MergeRule.

**Comment by kendonB** [comment]
This looks fixed! Thanks!
