### ISSUE TITLE
words.txt crashes caster

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#339]
Possibly related #152.

I'm just using the example from the docs and I'm trying out the latest develop branch:

```
# words.txt
<<<SPEC>>>
shock -> earthquake
<<<NOT_SPECS>>>
sauce -> up
dunce -> down
lease -> left
```

And the caster output:

```
 UserDirectory: C:\Users\kendon\Documents\caster
UnimacroDirectory: C:\NatLink\Unimacro
start of natlinkstartup
Vocola not active
Global rule filter from file 'words.txt' activated ...
<type 'exceptions.UnicodeDecodeError'>
'ascii' codec can't decode byte 0x83 in position 52: ordinal not in range(128)
<traceback object at 0x0F150F08>
  File "C:\Users\kendon\Documents\caster\caster\lib\dfplus\merge\ccrmerger.py", line 354, in _run_filters
    filter_fn(merge_pair)

  File "C:\Users\kendon\Documents\caster\caster\lib\dfplus\merge\gfilter.py", line 187, in spec_override_from_config
    new_choice = Choice(extra.name, choices)

  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\grammar\elements_compound.py", line 323, in __init__
    child = Compound(spec=k, value=v, extras=extras)

  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\grammar\elements_compound.py", line 270, in __init__
    element = self._parser.parse(spec)

  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 52, in parse
    for result in generator:

  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 413, in parse
    try: path[-1].next()

  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 472, in parse
    try: path[-1].next()

  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 413, in parse
    try: path[-1].next()

  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 547, in parse
    for result in child.parse(state):

  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 413, in parse
    try: path[-1].next()

  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 708, in parse
    while not state.finished() and state.peek(1) in self._set:

Filter function 'spec_override_from_config' failed.
Error loading _caster from C:\Users\kendon\Documents\caster\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 317, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\kendon\Documents\caster\_caster.py", line 163, in <module>
    _NEXUS.merger.merge(MergeInf.BOOT)
  File "C:\Users\kendon\Documents\caster\caster\lib\dfplus\merge\ccrmerger.py", line 257, in merge
    else: base = self._compatibility_merge(mp, base, rule)
  File "C:\Users\kendon\Documents\caster\caster\lib\dfplus\merge\ccrmerger.py", line 191, in _compatibility_merge
    base = rule if base is None else base.merge(rule)
  File "C:\Users\kendon\Documents\caster\caster\lib\dfplus\merge\mergerule.py", line 112, in merge
    mcontext=context)
  File "C:\Users\kendon\Documents\caster\caster\lib\dfplus\merge\mergerule.py", line 65, in __init__
    MappingRule.__init__(self, name, mapping, extras, defaults, exported)
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\grammar\rule_mapping.py", line 146, in __init__
    c = Compound(spec, elements=self._extras, value=value)
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\grammar\elements_compound.py", line 270, in __init__
    element = self._parser.parse(spec)
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 52, in parse
    for result in generator:
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 413, in parse
    try: path[-1].next()
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 472, in parse
    try: path[-1].next()
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 413, in parse
    try: path[-1].next()
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 547, in parse
    for result in child.parse(state):
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 413, in parse
    try: path[-1].next()
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\parser.py", line 708, in parse
    while not state.finished() and state.peek(1) in self._set:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 52: ordinal not in range(128)
-- skip unchanged wrong grammar file: C:\Users\kendon\Documents\caster\_caster.py
-- skip unchanged wrong grammar file: C:\Users\kendon\Documents\caster\_caster.py
natlinkmain started from C:\NatLink\NatLink\MacroSystem\core:
  NatLink version: 4.1uniform
  DNS version: 15
  Python version: 27
  Windows Version: 7

User defined macro's (UserDirectory) enabled: C:\Users\kendon\Documents\caster
```

**Comment by kendonB** [comment]
Closing as I think I need to update dragonfly
