### ISSUE TITLE
Bug while editing extras in rule

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#54]
I start with this rule:
```python
from dragonfly import Repeat, Function, Choice

from castervoice.lib import navigation
from castervoice.lib.actions import Key, Text, Mouse
from castervoice.lib.const import CCRType
from castervoice.lib.actions import Text
from castervoice.lib.ctrl.mgr.rule_details import RuleDetails
from castervoice.lib.merge.mergerule import MergeRule
from castervoice.lib.merge.additions import IntegerRefST
from castervoice.lib.merge.state.short import R
from castervoice.lib.ccr.standard import SymbolSpecs

actions_dict = {
            "select | grab": "",
            "stoosh": "c-c",
            "cut": "c-x",
            "spark": "c-v",
            "clear": "backspace"
        }
class NPPCCRRule(MergeRule):
    pronunciation = "notepad plus plus continuous"
    
    mapping = {
        SymbolSpecs.COMMENT:
            R(Key("c-q")),
        "<action> (line | lines) <ln1> [(by | to) <ln2>]":
            R(Function(navigation.action_lines)),
    }
    extras = [
        IntegerRefST("ln1", 1, 10000),
        IntegerRefST("ln2", 1, 10000),
        Choice("action", actions_dict)
    ]
    defaults = {"ln2": ""}


def get_rule():
    return NPPCCRRule, RuleDetails(executable="notepad++", ccrtype=CCRType.APP)
```
then edit it to become this rule which should be the same as the above as it just copy-pastes the dict into the `Choice` call directly:
```python
from dragonfly import Repeat, Function, Choice

from castervoice.lib import navigation
from castervoice.lib.actions import Key, Text, Mouse
from castervoice.lib.const import CCRType
from castervoice.lib.actions import Text
from castervoice.lib.ctrl.mgr.rule_details import RuleDetails
from castervoice.lib.merge.mergerule import MergeRule
from castervoice.lib.merge.additions import IntegerRefST
from castervoice.lib.merge.state.short import R
from castervoice.lib.ccr.standard import SymbolSpecs

actions_dict = {
            "select | grab": "",
            "stoosh": "c-c",
            "cut": "c-x",
            "spark": "c-v",
            "clear": "backspace"
        }
class NPPCCRRule(MergeRule):
    pronunciation = "notepad plus plus continuous"
    
    mapping = {
        SymbolSpecs.COMMENT:
            R(Key("c-q")),
        "<action> (line | lines) <ln1> [(by | to) <ln2>]":
            R(Function(navigation.action_lines)),
    }
    extras = [
        IntegerRefST("ln1", 1, 10000),
        IntegerRefST("ln2", 1, 10000),
        Choice("action", {
            "select | grab": "",
            "stoosh": "c-c",
            "cut": "c-x",
            "spark": "c-v",
            "clear": "backspace"
        })
    ]
    defaults = {"ln2": ""}


def get_rule():
    return NPPCCRRule, RuleDetails(executable="notepad++", ccrtype=CCRType.APP)
```
and I get this error:
```
ERROR:engine.timer:Exception during timer callback: list index out of range
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\engines\base\timer.py", line 91, in call
    self.function()
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\reload\timer_reload_observable.py", line 18, in <lambda>
    get_engine().create_timer(lambda: self._update(), self._time_in_seconds)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\reload\base_reload_observable.py", line 35, in _update
    self._notify_listeners(file_path)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\reload\base_reload_observable.py", line 40, in _notify_listeners
    listener.receive(path_changed)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 233, in receive
    rule_class, details = self._content_loader.idem_import_module(module_name, ContentType.GET_RULE)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 90, in idem_import_module
    return fn()
  File "C:/Users/kmbel/.caster\rules\notepadplusplus_ccr.py", line 44, in get_rule
    return NPPCCRRule, RuleDetails(executable="notepad++", ccrtype=CCRType.APP)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\rule_details.py", line 30, in __init__
    frame = inspect.stack()[1]
  File "C:\Python27\Lib\inspect.py", line 1069, in stack
    return getouterframes(sys._getframe(1), context)
  File "C:\Python27\Lib\inspect.py", line 1047, in getouterframes
    framelist.append((frame,) + getframeinfo(frame, context))
  File "C:\Python27\Lib\inspect.py", line 1022, in getframeinfo
    lines, lnum = findsource(frame)
  File "C:\Python27\Lib\inspect.py", line 579, in findsource
    if pat.match(lines[lnum]): break
IndexError: list index out of range
```

**Comment by synkarius** [comment]
@kendonB Does this happen consistently? If so, THANK YOU. I knew about this but it only seemed to happen to me at random.

**Comment by kendonB** [comment]
This happens consistently with this particular edit.

**Comment by LexiconCode** [comment]
Reproducible on my machine as well consistently.

**Comment by synkarius** [comment]
This should be good to go. If you manage to get it to happen again, I can add a more dynamic fix, but I think this ought to do it.

**Comment by synkarius** [comment]
@kendonB please close this out once you have confirmed that the fix works.

**Comment by kendonB** [comment]
looks like this is working now. Thanks!
