### ISSUE TITLE
better error message when breaking due to a merge conflict?

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#60]
For those of us that actively maintain Caster and those that live on the bleeding edge getting updates all the time, it's often the case that we want to merge with someone else's branch. If this involves merge conflicts we get these big yucky error messages e.g.:

```python
An error occurred while importing '<module 'python' from 'C:/Users/kmbel/Documents/caster/castervoice\lib\ccr\python\python.py'>': Traceback (most recent call last):
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 133, in _reimport_module
    return reload_fn(module)
  File "C:/Users/kmbel/Documents/caster/castervoice\lib\ccr\python\python.py", line 39
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

ERROR:engine.timer:Exception during timer callback: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly2-0.18.0-py2.7.egg\dragonfly\engines\base\timer.py", line 91, in call
    self.function()
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\reload\timer_reload_observable.py", line 18, in <lambda>
    get_engine().create_timer(lambda: self._update(), self._time_in_seconds)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\reload\base_reload_observable.py", line 35, in _update
    self._notify_listeners(file_path)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\reload\base_reload_observable.py", line 49, in _notify_listeners
    listener.receive(path_changed)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\grammar_manager.py", line 233, in receive
    rule_class, details = self._content_loader.idem_import_module(module_name, ContentType.GET_RULE)
TypeError: 'NoneType' object is not iterable
```
Is it feasible to give a more useful error message here? Is this situation easily detectable within caster? Perhaps: "<rule_name> dropped due to a SyntaxError with "<<<<<<<<" detected. Do you have a git merge conflict? If so, please resolve to reload  <rule_name>.".

In this particular case, I do find that the rule comes back once I fix up the merge conflict so it looks like the system is robust to this simple situation which is great!

**Comment by kendonB** [comment]
It would actually also be good to handle SyntaxErrors in rules a bit more gracefully in general with something similar to a "<rule_name> dropped due to a SyntaxError. Please correct the syntax in <rule_name> to reload it."

**Comment by synkarius** [comment]
This is outside the scope of the rewrite and should be handled after the rewrite PR is merged.

**Comment by LexiconCode** [comment]
This could be moved to main repo when you have a chance.
