### ISSUE TITLE
Initialization fails if the settings file already exists

### ISSUE THREAD

**Issue by Versatilus** [synkarius/caster#61]
When I first initialize the Caster installation it loads without major issues. The settings file is created and saved to the disk. When I restart Dragon, however, you can see from the log that it fails to load with a very bizarre error. I've had my fill of the weird for tonight, so I'm leaving this here for you to ponder. It really has me scratching my head.

**initialization success**
```
IOError: Could not find settings file: C:\NatLink\NatLink\MacroSystem\caster\bin\data\settings.json
Initializing file...


settings values changed:  75
*- Starting Caster v 0.4.7 -*

Attempting to load CCR anyway...
<type 'exceptions.TypeError'>
'NoneType' object has no attribute '__getitem__'
<traceback object at 0x0D656C38>
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 47, in <module>
    recording.load_alias_rules()

  File "C:\NatLink\NatLink\MacroSystem\caster\lib\recording.py", line 94, in load_alias_rules
    rewrite_alias_module(None, None)

  File "C:\NatLink\NatLink\MacroSystem\caster\lib\recording.py", line 66, in rewrite_alias_module
    if match_object[0][0]==a[0]:
```

**initialization failure**
```
*- Starting Caster v 0.4.7 -*

Attempting to load CCR anyway...
<type 'exceptions.TypeError'>
'NoneType' object has no attribute '__getitem__'
<traceback object at 0x0D545CD8>
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 47, in <module>
    recording.load_alias_rules()

  File "C:\NatLink\NatLink\MacroSystem\caster\lib\recording.py", line 94, in load_alias_rules
    rewrite_alias_module(None, None)

  File "C:\NatLink\NatLink\MacroSystem\caster\lib\recording.py", line 66, in rewrite_alias_module
    if match_object[0][0]==a[0]:

Error loading _caster from C:\NatLink\NatLink\MacroSystem\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 340, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 82, in <module>
    class MainRule(MappingRule):
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 156, in MainRule
    generate_CCR_choices.__func__()
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 89, in generate_CCR_choices
    return Choice("ccr_mode", choices)
  File "c:\programming\dragonfly\dragonfly\grammar\elements_compound.py", line 323, in __init__
    child = Compound(spec=k, value=v, extras=extras)
  File "c:\programming\dragonfly\dragonfly\grammar\elements_compound.py", line 270, in __init__
    element = self._parser.parse(spec)
  File "c:\programming\dragonfly\dragonfly\parser.py", line 52, in parse
    for result in generator:
  File "c:\programming\dragonfly\dragonfly\parser.py", line 413, in parse
    try: path[-1].next()
  File "c:\programming\dragonfly\dragonfly\parser.py", line 472, in parse
    try: path[-1].next()
  File "c:\programming\dragonfly\dragonfly\parser.py", line 413, in parse
    try: path[-1].next()
  File "c:\programming\dragonfly\dragonfly\parser.py", line 547, in parse
    for result in child.parse(state):
  File "c:\programming\dragonfly\dragonfly\parser.py", line 413, in parse
    try: path[-1].next()
  File "c:\programming\dragonfly\dragonfly\parser.py", line 708, in parse
    while not state.finished() and state.peek(1) in self._set:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 52: ordinal not in range(128)
```

**Comment by synkarius** [comment]
Good catch. This had to do with me making "alias" commands overwriteable. Should be okay now.

**Comment by Versatilus** [comment]
I'm happy to see the back with the aliases file text, but my initial problem still remains. Caster fails to load after encountering a problem setting up the CCR choices in line 89 of _caster.py.

After doing some supercollider programming, that is, smashing things together at a high rate of speed and looking at what's left, I can't see any logical reason for the failure. It's failing to parse the CCR choice "punctuation" with an error that just doesn't make any sense.

I would appreciate your continuing to look into it while I reinstall Python and Natlink again to see if there's something broken in my setup. I'm really looking forward to incorporating Caster into my system.

**Comment by Versatilus** [comment]
I don't know what broke, but after freshly reinstalling Natlink and all of its dependencies, Caster works perfectly.

**Comment by synkarius** [comment]
Strange, but I'm glad it works now. :-)
