### ISSUE TITLE
Currently getting an error on startup

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#67]
```python
Error loading _caster from C:\Users\kmbel\Documents\caster\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\kmbel\Documents\caster\_caster.py", line 33, in <module>
    control.init_nexus(_content_loader)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\control.py", line 7, in init_nexus
    _NEXUS = Nexus(content_loader)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\nexus.py", line 83, in __init__
    self._load_and_register_all_content(rules_config, hooks_runner, transformers_runner)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\nexus.py", line 92, in _load_and_register_all_content
    content = self._content_loader.load_everything(rules_config)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 57, in load_everything
    rules = self._process_requests(rule_requests)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 106, in _process_requests
    content_item = self.idem_import_module(request.module_name, request.content_type)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 92, in idem_import_module
    return fn()
  File "C:/Users/kmbel/Documents/caster/castervoice\apps\vscode2.py", line 302, in get_rule
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\rule_details.py", line 31, in __init__
    self._filepath = RuleDetails._calculate_filepath_from_frame(stack, 1)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\rule_details.py", line 37, in _calculate_filepath_from_frame
    filepath = module.__file__.replace("\\", "/")
AttributeError: 'NoneType' object has no attribute '__file__'
-- skip unchanged wrong grammar file: C:\Users\kmbel\Documents\caster\_caster.py
-- skip unchanged wrong grammar file: C:\Users\kmbel\Documents\caster\_caster.py
```

**Comment by kendonB** [comment]
Fixed after running `find . -name "*.pyc" -type f -delete`
