### ISSUE TITLE
Chrome rule not loading

### ISSUE THREAD

**Issue by synkarius** [synkarius/Caster#9]
Reported by @kendonB in chat.

**Comment by kendonB** [comment]
Unfortunately am still seeing the problem. To reproduce:

1. Delete the `.caster` user folder
2. Kill all Dragon processes
3. Start Dragon again

In the status window I see:

```
Could not import 'firefox'. Module has errors: Traceback (most recent call last):
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 112, in _import_module
    return load_fn(module_name)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\kmbel\Documents\caster\castervoice\apps\firefox.py", line 18, in <module>
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\dfplus\merge\gfilter.py", line 125, in <module>
KeyError: 'SIMPLIFIED_FILTER_RULES_PATH'

Could not import 'chrome'. Module has errors: Traceback (most recent call last):
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 112, in _import_module
    return load_fn(module_name)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\kmbel\Documents\caster\castervoice\apps\chrome.py", line 20, in <module>
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\dfplus\merge\gfilter.py", line 125, in <module>
KeyError: 'SIMPLIFIED_FILTER_RULES_PATH'

Could not import 'jetbrains'. Module has errors: Traceback (most recent call last):
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 112, in _import_module
    return load_fn(module_name)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\kmbel\Documents\caster\castervoice\apps\jetbrains.py", line 8, in <module>
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\dfplus\merge\gfilter.py", line 125, in <module>
KeyError: 'SIMPLIFIED_FILTER_RULES_PATH'


*- Starting Caster v 1.0.0 -*
natlinkmain started from C:\NatLink\NatLink\MacroSystem\core:
  NatLink version: 4.1whiskey3
  DNS version: 15
  Python version: 27
  Windows Version: 10
User defined macro's (UserDirectory) enabled: C:\Users\kmbel\Documents\caster
----------------------------------------
```

**Comment by kendonB** [comment]
Looks like it was caused by some linger `.pyc` files from the other branch that get ignored by git. I ran ` find . -name "*.pyc" -type f -delete` before compiling the first time and it now seems to work.
